fix: enable acquisition ContentType transfer
# Motivation

Commit bfe0178454b772d8c4c8b54edace6e2518f9e4c0
introduced `acquisition` as a new contentType to
upload. Unfortunately, the code that is supposed
to filter out non-web archive kafka messages was
not updated, which made it crash with the error
message below.

The reason why it was not discovered before much
later was that this code is only run when starting
a new `transfer` session.

# Error

This commit fixes the following error:

```
failed to send error message to Teams, cause: `
failed to send message to teams, cause: `
ErrTransport: Post "https:": http: no Host in
request URL``
Error: transfer error, cause: `failed to filter
out relevant messages, original error: 'found
content type 'acquisition' in message '
{Date:2024-01-25T09:46:42.019 ContentCategory:nettarkiv
ContentType:acquisition Identifier:<identifier> Urn:<URN> Path:<path>}', expected 'warc''`
failed to execute command, got error: 'transfer
error, cause: `failed to filter out relevant
messages, original error: 'found content type
'acquisition' in message '{Date:2024-01-25T09:46:42.019
ContentCategory:nettarkiv ContentType:acquisition
Identifier:<identifier> Urn:<URN> Path:<path>}',
expected 'warc''`'
```

The fix is to allow the `acquisition` contentType
to be allowed to be transferred.