feat: add top level interface
In order to get early feedback on the design of this project, only the
interface of the service is implemented by this commit.

This project will provide two features, continuously sending data to
digital storage and continuously verifying that the data sent to storage
has been properly stored.

The actual implementation details will be added and properly described
in later commits.

Each command `send` and `verify` both require that the user passes a
`kafka-endpoints` argument

Examples of the interfaces can be found below
```
$ hermetic --help
hermetic - sends and verifies data for digital storage

Usage:
  hermetic [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  send        Continuously sends data to digital storage
  verify      Continuously verifies uploaded data responses

Flags:
  -h, --help                      help for hermetic
      --kafka-endpoints strings   list of kafka endpoints

Use "hermetic [command] --help" for more information about a command.
```

```
$ hermetic send --help
Continuously sends data to digital storage

Usage:
  hermetic send [flags]

Flags:
  -h, --help                          help for send
      --stage-artifacts-root string   path to the root directory with the following content structure:
                                      /stage-artifacts-root
                                      ├── /kommuner_2023-20230611002729-0035-veidemann-contentwriter-568c6f8545-frvcm
                                      │   ├── /kommuner_2023-20230611002729-0035-veidemann-contentwriter-568c6f8545-frvcm.warc.gz
                                      │   └── /checksum_transferred.md5
                                      └── /kommuner_2023-20230611002730-0036-veidemann-contentwriter-568c6f8545-frvcm
                                          ├── /kommuner_2023-20230611002730-0036-veidemann-contentwriter-568c6f8545-frvcm.warc.gz
                                          └── /checksum_transferred.md5
                                      ... etc
      --transfer-topic string         name of transfer-topic

Global Flags:
      --kafka-endpoints strings   list of kafka endpoints
```

```
$ hermetic verify --help
Continuously verifies uploaded data responses

Usage:
  hermetic verify [flags]

Flags:
  -h, --help                  help for verify
      --reject-topic string   name of reject-topic

Global Flags:
      --kafka-endpoints strings   list of kafka endpoints
```

When some of the arguments are missing, the output will look like this
```
$ hermetic --kafka-endpoints 123,456 send
Error: required flag(s) "transfer-topic" not set
Usage:
  hermetic send [flags]

Flags:
  -h, --help                          help for send
      --stage-artifacts-root string   path to the root directory with the following content structure:
                                      /stage-artifacts-root
                                      ├── /kommuner_2023-20230611002729-0035-veidemann-contentwriter-568c6f8545-frvcm
                                      │   ├── /kommuner_2023-20230611002729-0035-veidemann-contentwriter-568c6f8545-frvcm.warc.gz
                                      │   └── /checksum_transferred.md5
                                      └── /kommuner_2023-20230611002730-0036-veidemann-contentwriter-568c6f8545-frvcm
                                          ├── /kommuner_2023-20230611002730-0036-veidemann-contentwriter-568c6f8545-frvcm.warc.gz
                                          └── /checksum_transferred.md5
                                      ... etc
      --transfer-topic string         name of transfer-topic

Global Flags:
      --kafka-endpoints strings   list of kafka endpoints

failed to execute command, got error: 'required flag(s) "transfer-topic" not set'
exit status 1
```